name: CI/CD

on:
  push:
    branches: [ main ]
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build docker containers
        run: |
          cd build
          docker-compose build
      
      - name: Run docker containers
        run: |
          cd build
          docker-compose up -d
        
      - name: Run tests
        run: |
          cd build
          cd images
          cd api
          npm run test
          
  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build docker containers
        run: |
          cd build
          docker-compose build
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Publish
        run: docker-compose push
